Add number mask and validation
MakersNetwork/agenda-saude pull request #103
Opened 2021-01-06 17:10 UTC by schaiana

Foi adicionada uma máscara para formatar os números de telefone digitados nos campos **telefone** e **telefone secundário**.
Antes, era possível digitar qualquer caractere, agora só números e formatados dentro de um padrão: (xx) xxxx-xxxx ou (xx) yxxxx-xxxx.

Também é feita uma validação no backend, para verificar se o número é válido. Essa validação, inicialmente, foi feita com uma gema (PhoneLib), mas foi substituída por um RegEX, pois na gema não era possível aceitar um número de celular digitado sem o 9 no início.

## :computer: SCREENSHOTS

![Screenshot from 2021-01-06 14-08-11](https://user-images.githubusercontent.com/31892261/103798592-af022780-5028-11eb-9dd8-cddcef2b3202.png)

## TESTS
Para testar, basta adicionar um paciente e inserir um número de telefone válido, observando a máscara sendo aplicada e salvando com sucesso.
Outra opção de testes é editar o número.

P.S.: Não foram feitos nesse PR tratamentos de erro caso o usuário digite um número inválido.
Será aberta uma nova atividade para isso.
P.S.²: Na hora do merge com a master, podemos fazer um squash para tirar os commits envolvendo a PhoneLib

2021-01-06 19:55 UTC, iago-silva requested changes

2021-01-06 19:55 UTC, iago-silva commented on app/assets/javascripts/application.js
> +  $('.sp_celphones').mask(SPMaskBehavior, spOptions);
Acho que é melhor deixar o padrão de separar as palavras das classes CSS com hífen (-) 

```suggestion
  $('.sp-celphones').mask(SPMaskBehavior, spOptions);
```

2021-01-06 19:55 UTC, iago-silva commented on app/validators/phone_format_validator.rb
> +class PhoneFormatValidator < ActiveModel::EachValidator #stardard lib rails
```suggestion
class PhoneFormatValidator < ActiveModel::EachValidator
```

2021-01-06 19:55 UTC, iago-silva commented on app/assets/javascripts/application.js
> +    }
```suggestion
    field.mask(SPMaskBehavior.apply({}, arguments), options);
  }
```

2021-01-06 19:55 UTC, iago-silva commented on app/views/patients/registrations/new.html.erb
> +      <%= f.text_field :other_phone, autofocus: true, autocomplete: "other_phone", required: false, class: "form-control sp_celphones" %>
```suggestion
      <%= f.text_field :other_phone, autofocus: true, autocomplete: "other_phone", required: false, class: "form-control sp-celphones" %>
```

2021-01-06 19:55 UTC, iago-silva commented on app/views/patients/registrations/new.html.erb
> +      <%= f.text_field :phone, autofocus: true, autocomplete: "phone", required: true, class: "form-control sp_celphones" %>
```suggestion
      <%= f.text_field :phone, autofocus: true, autocomplete: "phone", required: true, class: "form-control sp-celphones" %>
```

2021-01-06 19:55 UTC, iago-silva commented on app/views/patients/registrations/edit.html.erb
> +      <%= f.text_field :other_phone, autofocus: true, autocomplete: "other_phone", required: false, class: "form-control sp_celphones" %>
```suggestion
      <%= f.text_field :other_phone, autofocus: true, autocomplete: "other_phone", required: false, class: "form-control sp-celphones" %>
```

2021-01-06 19:55 UTC, iago-silva commented on app/views/patients/registrations/edit.html.erb
> +      <%= f.text_field :phone, autofocus: true, autocomplete: "phone", required: true, class: "form-control sp_celphones" %>
```suggestion
      <%= f.text_field :phone, autofocus: true, autocomplete: "phone", required: true, class: "form-control sp-celphones" %>
```

2021-01-12 18:37 UTC, iago-silva approved these changes

2021-01-18 12:10 UTC, pedroCervi commented
Alous!!

Ele retornou json pra mim, isso é pq n estamos tratando o erro? Que se for o caso acho que temos que segurar esse pr até termos esse tratamento pra não confundir o usuário ali com o json :sweat_smile: 

![phone-mask](https://user-images.githubusercontent.com/21227797/104913722-cddbb480-596c-11eb-8abf-69c58e66342d.gif)

2021-01-18 12:12 UTC, pedroCervi requested changes
Tá bunitu :star: :star2:  Só acho que temos que ver ali a questão do tratamento do erro antes do merge. Que no meu caso ele mostoru o json na tela :thinking:

2021-01-18 13:02 UTC, schaiana commented
> Alous!!
> 
> Ele retornou json pra mim, isso é pq n estamos tratando o erro? Que se for o caso acho que temos que segurar esse pr até termos esse tratamento pra não confundir o usuário ali com o json sweat_smile
> 
> ![phone-mask](https://user-images.githubusercontent.com/21227797/104913722-cddbb480-596c-11eb-8abf-69c58e66342d.gif)

2021-01-18 13:03 UTC, schaiana commented
> Tá bunitu star star2 Só acho que temos que ver ali a questão do tratamento do erro antes do merge. Que no meu caso ele mostoru o json na tela thinking

Oi! Tá assim em todo o código, eu só deixei aqui também e propus em reunião a gente abrir uma atividade pra não renderizar o erro pra um json.

2021-01-18 13:37 UTC, pedroCervi commented
> > Tá bunitu star star2 Só acho que temos que ver ali a questão do tratamento do erro antes do merge. Que no meu caso ele mostoru o json na tela thinking
> 
> Oi! Tá assim em todo o código, eu só deixei aqui também e propus em reunião a gente abrir uma atividade pra não renderizar o erro pra um json.

@schaiana Vamos subir esse cara, só fiz uma altração para ter o alert ao invés do json, ai vamos fazer um card e melhoria disso pra puxar depois

2021-01-18 13:53 UTC, pedroCervi approved these changes

2021-01-18 14:42 UTC, GabrielaMafra approved these changes

2021-01-18 17:35 UTC, merged