criado partials para colocar alguns codigos html que estavam sendo re…
MakersNetwork/agenda-saude pull request #140
Opened 2021-02-04 18:12 UTC by RafaelaMachado

Hello, mandei para partials uns codigos html que estavam muito repetitivos, em outro PR vou vasculhar mais o projeto para continuar com essa melhoria

2021-02-04 18:33 UTC, iago-silva requested changes

2021-02-04 18:33 UTC, iago-silva commented on app/views/home/home_teste_rapido.html.erb
> +<%= render partial: "orientation" %>
Você chegou a criar essa partial?

2021-02-04 18:33 UTC, iago-silva commented on app/views/home/index.html.erb
> +<%= render partial: "orientation_text" %>
Você chegou a criar essa partial?

2021-02-04 19:57 UTC, iago-silva approved these changes

2021-03-23 16:41 UTC, alfakini approved these changes

2021-03-23 16:41 UTC, merged