Fix time slot index view
MakersNetwork/agenda-saude pull request #141
Opened 2021-02-05 05:06 UTC by Mat-Bit

Olá!

Neste PR é feito modificações na view `time_slot.index.html` para que:

- Não apareça o *card* de agendamento atual se o horário de início do mesmo já passou, impossibilitando que o paciente possa cancelar / substituir este agendamento;
- Não exibir o *Accordion* de uma unidade se a mesma está ativa, porém sem nenhum agendamento disponível para o dia selecionado.

### Antes:

![time_slot_view_before](https://user-images.githubusercontent.com/19494561/106992173-98014300-6756-11eb-9906-7b0610e41452.gif)

### Depois:

![time_slot_view_after](https://user-images.githubusercontent.com/19494561/106992193-a18aab00-6756-11eb-8a39-f21ca2044327.gif)

2021-02-05 13:37 UTC, edrd-f requested changes

2021-02-05 13:37 UTC, edrd-f commented on app/controllers/time_slot_controller.rb
> +        next unless appointments.present?
O `.present?` carrega todos os registros e verifica se o array tem pelo menos um item. Melhor usar `.exists?`, que otimiza a query pra determinar apenas se existe um registro.

```suggestion
        next unless appointments.exists?
```

2021-02-05 13:45 UTC, edrd-f approved these changes

2021-02-06 18:37 UTC, pedroCervi approved these changes

2021-02-06 18:37 UTC, merged