Melhoria para as telas de check-in e check-out
MakersNetwork/agenda-saude pull request #144
Opened 2021-02-05 15:17 UTC by Mat-Bit

Olá pessoal!

Neste PR propõe melhorias nas telas de `ubs/checkin.html.erb` e `ubs/chekcout.html.erb`:

### Check-in:

- Mostrar por padrão pacientes que tenham agendamento entre `[Time.zone.now-30.minutes..Time.zone.now+40minutes]` (valores empíricos), para que seja possível visualizá-los sem a necessidade de realizar busca por nome ou CPF;
- Ao buscar por nome ou CPF do paciente, vai retornar agendamentos entre `[Time.zone.now-2.days..Time.zone.now+2.days]`, para caso o paciente venha na data incorreta, o operador conseguir visualizar este atendimento e orientar o paciente do dia correto;
- Ordená-los por data e hora de início do agendamento.

### Check-out:

- Ordenar os agendamentos por data e hora de início do agendamento.

### Motivos:

Facilitar o uso do sistema para o operador para que consiga localizar de forma mais prática os pacientes que precisam fazer check-in / check-out.

2021-02-05 16:52 UTC, iago-silva requested changes

2021-02-05 16:52 UTC, iago-silva commented on app/controllers/ubs_controller.rb
> +    render 'ubs/checkin'
Não precisa dessa linha, o rails já vai buscar por `controlador/action`

2021-02-05 16:58 UTC, iago-silva commented
Não seria bom deixar claro para o operador que na tela de chekin só tá sendo exibido por padrão os agendamentos que tão nesse intervalo de tempo?

2021-02-05 17:03 UTC, iago-silva commented
> Ao buscar por nome ou CPF do paciente, vai retornar agendamentos entre [Time.zone.now-2.days..Time.zone.now+2.days], para caso o paciente venha na data incorreta, o operador conseguir visualizar este atendimento e orientar o paciente do dia correto;

Mesma coisa aqui... Deixar claro o intervalo de tempo para evitar confusões

2021-03-23 18:08 UTC, closed without merging

2021-03-23 18:08 UTC, Mat-Bit commented
Outdated