Fix security issue on cancel action
MakersNetwork/agenda-saude pull request #149
Opened 2021-02-07 02:36 UTC by edrd-f

Olá!

PR simples para corrigir uma brecha de segurança no cancelamento de agendamentos. A action estava aceitando qualquer ID de agendamento, sendo possível cancelar agendamentos de outros pacientes. 

Coloquei em uma transação também para evitar inconsistências de dados caso a atualização do agendamento falhe.

2021-02-07 18:39 UTC, iago-silva requested changes

2021-02-07 18:39 UTC, iago-silva commented on app/controllers/time_slot_controller.rb
> +        .update_all(patient_id: nil)
```suggestion
        .find(id: cancel_params[:appointment_id])
        .update(patient_id: nil)
```

Que tal deixar assim mesmo para otimizar a query?

2021-02-08 12:15 UTC, edrd-f commented on app/controllers/time_slot_controller.rb
> +        .update_all(patient_id: nil)
Então, apesar de ficar mais idiomático, isso faria duas queries, uma pro `find` e outra pro `update`. Fiz com o `update_all` porque assim vira de fato uma instrução `UPDATE`. Só preciso verificar a questão do `@current_patient.appointments.where`, mas pelo que eu lembre ele também já vai restringir a busca aos agendamentos do paciente.

2021-02-08 13:13 UTC, iago-silva commented on app/controllers/time_slot_controller.rb
> +        .update_all(patient_id: nil)
Boa!!! Vi nos logs aqui que o `find` + `update` faz mais buscas no banco.

2021-02-08 13:24 UTC, iago-silva commented on app/controllers/time_slot_controller.rb
> +        .update_all(patient_id: nil)
Só ainda não sei qual vai ser mais vantajoso, usando o `find` + `update` adiciona mais query, mas são limitadas a 1 registro. Também tem a questão de ficar mais legível

2021-02-08 15:33 UTC, edrd-f commented on app/controllers/time_slot_controller.rb
> +        .update_all(patient_id: nil)
Como o `where` tá buscando pela PK, o `update_all` vai atualizar um registro só também :slightly_smiling_face:

2021-02-14 00:14 UTC, pedroCervi approved these changes
:ship:

2021-02-14 00:14 UTC, merged