Update status appointment logic
MakersNetwork/agenda-saude pull request #158
Opened 2021-02-17 20:21 UTC by Mat-Bit

Olá Makers,

Neste PR foi proposto ajuste no **Status de Agendamento** na página inicial.

### Mudanças

1. Limitar a busca por vagas disponíveis para `SLOTS_WINDOW_IN_DAYS` (Obs.: Se alterado o valor dessa variável em `time_slot_controller.rb`, o valor precisa ser alterado também em `home_controller.rb`)
2. Juntar as condições da Unidade estar ativa ou não ter vagas disponíveis para exibir a mensagem: "Aguardando novas doses"

![fix_appontment_status](https://user-images.githubusercontent.com/19494561/108263027-78015480-7144-11eb-8344-311cb44134a2.gif)

2021-02-17 21:41 UTC, edrd-f requested changes

2021-02-17 21:41 UTC, edrd-f commented on app/controllers/home_controller.rb
> +  SLOTS_WINDOW_IN_DAYS = 3
Como é um refactor simples, acredito que já vale fazermos pra eliminar o risco de esquecermos de alterar um dos locais. Pensei em colocarmos na classe `Appointment`:

###### app/models/appointment.rb
```ruby
class Appointment < ApplicationRecord
  SLOTS_WINDOWS_IN_DAYS = 3

  ...
end
```

E referenciarmos aqui e no `TimeSlotController`.

2021-02-17 21:41 UTC, edrd-f commented on app/controllers/home_controller.rb
> +    @appointments_available_in_slot_window = Appointment.where(start: Time.zone.now..(Time.zone.now + SLOTS_WINDOW_IN_DAYS.days).end_of_day, patient_id: nil)
Acho que o `present?` vai carregar todos os registros em um array e depois verificar se tem algum item, desnecessariamente. Nesse caso é melhor usarmos o `exists?`. Pra ficar coerente com essa mudança, a variável poderia se chamar `@is_scheduling_available`. Eu incluiria também a verificação de UBS ativa aqui:

```ruby
@is_scheduling_available = Ubs.active.exists? && Appointment.where(
  start: Time.zone.now..(Time.zone.now + Appointment::SLOTS_WINDOW_IN_DAYS.days).end_of_day, 
  patient_id: nil
).exists?
```

2021-02-17 21:41 UTC, edrd-f commented on app/views/home/index.html.erb
> +        <% if Ubs.where(active: true).blank? || !@appointments_available_in_slot_window.present? %>
Referente ao comentário anterior:

```suggestion
        <% unless @is_scheduling_available %>
```

2021-02-17 22:03 UTC, iago-silva commented on app/controllers/home_controller.rb
> +  SLOTS_WINDOW_IN_DAYS = 3
Outra alternativa seria colocar essa informação em uma variável de ambiente

2021-02-17 22:18 UTC, edrd-f commented on app/controllers/home_controller.rb
> +  SLOTS_WINDOW_IN_DAYS = 3
Boa, @iago-silva. Concordo.

```suggestion
  ENV['SLOTS_WINDOW_IN_DAYS']&.to_i || 3
```

2021-02-17 22:32 UTC, edrd-f commented on app/controllers/home_controller.rb
> +    @appointments_available_in_slot_window = Appointment.where(start: Time.zone.now..(Time.zone.now + SLOTS_WINDOW_IN_DAYS.days).end_of_day, patient_id: nil)
Existe um outro cenário ainda:

- Ubs 1 ativa e sem slots ou todos ocupados
- Ubs 2 desativada e com slots disponíveis dentro da janela

Com esse dataset o `@is_scheduling_available` seria `true`, mas por enquanto só temos uma Ubs então não pode acontecer. Porém, futuramente seria legal pensarmos em extrair essa lógica do controller para o model e verificarmos a Ubs dos appointments:

```ruby
@is_scheduling_available = Appointment.free.within_allowed_window.exists?

# appointment.rb

class Appointment
  def self.free
    joins(:ubs).where(ubs: { active: true }).where(patient_id: nil)
  end

  def self.within_allowed_window
    where(start: Time.zone.now..(Time.zone.now + SLOTS_WINDOW_IN_DAYS).end_of_day)
  end

  # ...
end
```

2021-02-20 00:40 UTC, Mat-Bit commented on app/controllers/home_controller.rb
> +    @appointments_available_in_slot_window = Appointment.where(start: Time.zone.now..(Time.zone.now + SLOTS_WINDOW_IN_DAYS.days).end_of_day, patient_id: nil)
Muito bom @edrd-f :smiley: 
Apliquei essa sugestão para lidar com mais de uma unidade, fiz num novo commit.
Pelo que testei funcionou, mas quanto mais teste, melhor rs

2021-02-20 00:41 UTC, Mat-Bit commented on app/views/home/index.html.erb
> +        <% if Ubs.where(active: true).blank? || !@appointments_available_in_slot_window.present? %>
Alterações aplicadas no novo commit.

2021-02-20 13:48 UTC, edrd-f commented on app/controllers/home_controller.rb
> +    @appointments_available_in_slot_window = Appointment.where(start: Time.zone.now..(Time.zone.now + SLOTS_WINDOW_IN_DAYS.days).end_of_day, patient_id: nil)
Maravilha! Vou testar aqui também

2021-02-23 00:02 UTC, edrd-f approved these changes
Testei e a princípio tá tudo ok.

2021-02-26 15:09 UTC, pedroCervi approved these changes

2021-02-26 17:05 UTC, merged