Allow previous appointment logic
MakersNetwork/agenda-saude pull request #167
Opened 2021-02-28 19:08 UTC by pedroCervi

Pessoal, pensei aqui na seguinte lógica:

A regra de permitir agendamento não é cumulativa, logo, quando ela muda, pacientes com agendamento em haver mas que sairam da regra deixam de poder ver/cancelar ou se reagendar. Fiz uma modificação no `can_schedule?`. Ou seja, todos que ja tem agendamento no futuro ou que entram nas condições de agendamento podem ver/substituir/cancelar.

O unico porem é, se cancelar o sujeito perde a capacidade de pegar de volta porque ele fica com seus agendamentos futuros nulos. Me parece ok.

MEU DEUS COMO É BOM PODER TESTAR ISSO!!!!

huiahuiahui 

bom domingo.

2021-03-01 00:15 UTC, edrd-f commented
@pedroCervi fiz um rebase da tua branch porque a base teve squash, então deu conflito e os diffs ficaram repetidos. Verifica se as mudanças tão certas, por favor?

2021-03-01 01:30 UTC, iago-silva requested changes

2021-03-01 01:53 UTC, edrd-f commented on app/models/patient.rb
> +  end
Complementando à lógica do @iago-silva: 

```suggestion
  def has_future_appointments?
    appointments
      .where('start >= ? AND active = TRUE', Time.zone.now)
      .exists?
  end
```

---

### .present? vs .exists?

`Appointment.where(patient_id: nil)` 

...

`.present?`:

```
Appointment Load (2.5ms)  SELECT "appointments".* FROM "appointments" WHERE "appointments"."patient_id" IS NULL
```

`.exists?`:

```
Appointment Exists? (0.5ms)  SELECT 1 AS one FROM "appointments" WHERE "appointments"."patient_id" IS NULL LIMIT $1
```

`.present?` = carregamento dos registros em array e check se array não é vazio.
`.exists?` = verifica se o retorno do banco é `1`. Query é otimizada também.

2021-03-01 02:40 UTC, iago-silva commented on app/models/patient.rb
> +  end
Show! Vou fechar a sugestão lá

2021-03-01 11:41 UTC, pedroCervi commented on spec/cypress/integration/patient/appointment.js
> +        cy.get('[data-cy=updatePatientButton]').click()
bouaa

2021-03-01 11:58 UTC, pedroCervi commented on spec/cypress/integration/patient/appointment.js
> +        cy.get('[data-cy=updatePatientButton]').click()
Só tive que rodar um `cy.visit('/')` como se fosse um refresh da página. Pq no scenario eu mexo direto no banco mas a pagina não ta atualizada.

2021-03-01 12:28 UTC, edrd-f approved these changes

2021-03-01 21:09 UTC, iago-silva commented on spec/cypress/integration/patient/appointment.js
> +        cy.get('[data-cy=updatePatientButton]').click()
Exato!

2021-03-01 21:15 UTC, iago-silva requested changes

2021-03-01 21:15 UTC, iago-silva commented on spec/cypress/app_commands/scenarios/young_marvin_son_of_tristeza.rb
> +patient = Patient.find_by(cpf: command_options['cpf'])
Acho que seria melhor você criar o paciente aqui. Aí lá nos testes você usa só 1 cenário pra cada lugar específico.

Ou você pode usar o outro cenário que já existia passando a data de nascimento por parâmetro `command_options['birth_date']`

2021-03-05 22:28 UTC, Mat-Bit commented
Pessoal, falei com o @pedroCervi já, mas gostaria de compartilhar a informação com os demais.

A regra mudou, o paciente que possui agendamento futuro mas não está no público alvo atual não pode se reagendar, somente ver e cancelar o agendamento.

Fiz um commit agora que tenta lidar com essa situação... passou nos testes mas gostaria do review para ver se está ok ou pode melhorar :grinning:

2021-03-06 16:39 UTC, Mat-Bit approved these changes

2021-03-13 12:54 UTC, pedroCervi commented on spec/cypress/app_commands/scenarios/young_marvin_son_of_tristeza.rb
> +patient = Patient.find_by(cpf: command_options['cpf'])
Concordo!

Vou fazer num card separado, que queria criar mais uns cenários de teste. Pode ser?

2021-03-13 16:56 UTC, iago-silva commented on spec/cypress/app_commands/scenarios/young_marvin_son_of_tristeza.rb
> +patient = Patient.find_by(cpf: command_options['cpf'])
Tá show!

2021-03-13 16:58 UTC, iago-silva approved these changes

2021-03-13 17:15 UTC, Mat-Bit approved these changes

2021-03-13 17:30 UTC, iago-silva requested changes

2021-03-13 17:30 UTC, iago-silva commented on app/controllers/time_slot_controller.rb
> +    @appointment = current_patient.appointments.order(:start).select(&:active?).last
Esse `.appointments.order(:start).select(&:active?)` tá sendo repetido em vários lugares, poderia ser um escopo no modelo de `Appointment`

2021-03-13 18:29 UTC, Mat-Bit commented on app/controllers/time_slot_controller.rb
> +    @appointment = current_patient.appointments.order(:start).select(&:active?).last
Alterado no model do `Patient`:

```ruby
def current_appointment
  appointments.order(:start).select(&:active?).last
end
```

2021-03-13 18:33 UTC, iago-silva commented on app/models/patient.rb
> +    # 'População com 80 anos ou mais' => ->(patient) { patient.age >= 80 },
Essa alteração era pra ter subido agora mesmo?

2021-03-13 19:13 UTC, Mat-Bit commented on app/models/patient.rb
> +    # 'População com 80 anos ou mais' => ->(patient) { patient.age >= 80 },
Vou precisar fazer o deploy dela agora, como alguns testes quebraram por causa dessa alteração, removi os mesmos e coloquei no card: [https://trello.com/c/IKd3KZba](https://trello.com/c/IKd3KZba)

2021-03-13 19:14 UTC, merged