test: when schedulling is disabled
MakersNetwork/agenda-saude pull request #281
Opened 2021-04-10 13:54 UTC by pedroCervi

Oi galera!

Só aumentando um pouco a cobertura do cypress.

Fiquei na dúvida se essa configuração global desabilita o agendamento ou só o reagendamento. Tipo. Se ativada, onde ela está agora tenho a impressão que vai desabilitar agendamentos como um todo :thinking: Mas seria só questão de mover o redirect para o scheduler ou algo do tipo.

2021-04-12 14:18 UTC, iago-silva requested changes

2021-04-12 14:18 UTC, iago-silva commented on spec/cypress/app_commands/scenarios/schedulling_is_enabled.rb
> +Rails.configuration.x.disabled_reschedule_toggle = ''
Como esse é o padrão, que tal criar só o cenários de desabilitação?

2021-04-12 21:20 UTC, pedroCervi commented on spec/cypress/app_commands/scenarios/schedulling_is_enabled.rb
> +Rails.configuration.x.disabled_reschedule_toggle = ''
O scenario do cypress não lidou bem com esse set. Vazou pros outros testes quando marquei true :cry:, ai tive que ter um scenario que 'volta ao normal'. Só setar a env tb não rola pq basicamente é uma informação que tem que ser passada pro rails server. Tenx alguma ideia de como poderíamos melhorar?

2021-04-12 21:24 UTC, iago-silva commented on spec/cypress/app_commands/scenarios/schedulling_is_enabled.rb
> +Rails.configuration.x.disabled_reschedule_toggle = ''
Adicionar essa linha 
```ruby
Rails.configuration.x.disabled_reschedule_toggle = ''
```

[aqui] (https://github.com/MakersNetwork/agenda-saude/blob/main/spec/cypress/support/custom.js#L2)

2021-04-12 21:27 UTC, iago-silva commented on spec/cypress/app_commands/scenarios/schedulling_is_enabled.rb
> +Rails.configuration.x.disabled_reschedule_toggle = ''
Aí é onde "limpa" o que foi feito no teste anterior

2021-04-18 15:28 UTC, jmonteiro commented
Esta foi uma funcionalidade que fiz para quando tivermos muitos acessos. A idéia é de que, quando ativado, pacientes iriam agendar aleatoriamente no primeiro local disponível, no primeiro horário disponível. Porém com várias unidades, a eficácia é  discutível.

Assim bastaria ligar e o sistema iria deixar de aceitar reagendamentos, mostrando a mensagem:

> Devido a alta demanda, o reagendamento está temporariamente desativado. Se você não poder comparecer no horário,  dia e local estabelecidos, tente reagendar novamente mais tarde, ou cancele seu agendamento e tente agende novamente mais tarde ou quando mais doses forem disponibilizadas.

Eu irei remover isso, para evitar confusão no código, já que nunca foi para o ar. Podemos tomar outras medidas para tornar o agendamento mais eficiente, ainda mais com várias unidades.

2021-04-18 15:47 UTC, alfakini approved these changes

2021-04-18 15:48 UTC, alfakini requested changes
Bloqueando por causa do comentário do jmonteiro.

2021-04-18 16:03 UTC, jmonteiro commented
Minha sugestão é remover esta funcionalidade (neste PR https://github.com/MakersNetwork/agenda-saude/pull/286).

2021-04-24 11:15 UTC, closed without merging