Consertando o problema que estava acontecendo ao substituir um agendamento
MakersNetwork/agenda-saude pull request #98
Opened 2020-12-04 01:29 UTC by Mat-Bit

Olá a todos(as),

Neste PR consertamos o problema que estava ocorrendo de quando um paciente que já tinha um agendamento marcado, clicava em algum outro horário disponível para substituir o agendamento anterior.

Problema que ocorre é que o agendamento anterior não é excluído, mantendo ocupada um horário que deveria ter ficado disponível com a substituição.

Outro erro que ocorre em decorrência deste primeiro, é ao cancelar o agendamento, é necessário um por um dos *n* agendamentos futuros que o paciente tenha se agendado, ao invés de excluir todos os agendamentos futuros de uma só vez.

### Problema
A animação abaixo exemplifica os erros mencionados:
![video_01_erro](https://user-images.githubusercontent.com/19494561/101109037-b3b06780-35b4-11eb-8965-a41acc474675.gif)

### Solução
A solução proposta para os erros citados acima é ilustrada na animação a seguir:
![video_02_feito](https://user-images.githubusercontent.com/19494561/101109739-51586680-35b6-11eb-98d2-24915460cf36.gif)

Não existe uma *issue* aberta para este problema.

2020-12-16 18:47 UTC, GabrielaMafra commented on app/controllers/time_slot_controller.rb
> +      end
Aqui você consegue usar o próprio relacionamento do ActiveRecord pra filtrar os appointmentes do paciente. E também dá pra usar o `destroy_all` pra não precisar iterar com o `each` :smile: 
```suggestion
      current_patient.appointments.where('start > ?', Time.zone.now).destroy_all
```

2020-12-16 18:47 UTC, GabrielaMafra commented on app/controllers/time_slot_controller.rb
> +
Não entendi por que você precisa destruir todos aqui também. Na linha 46 logo acima a gente já está destruindo o appointment atual do paciente, e acredito que isso seja suficiente nesse caso.
```suggestion
```

2020-12-17 03:23 UTC, Mat-Bit commented on app/controllers/time_slot_controller.rb
> +      end
Realmente @GabrielaMafra, mais otimizada e enxuta sua sugestão, toda diminuição na complexidade da operação (por menor que seja) é bem vinda :grinning:

2020-12-17 03:35 UTC, Mat-Bit commented on app/controllers/time_slot_controller.rb
> +
Coloquei aqui também pois caso o paciente tenha 2 ou mais agendamentos "adiantes" e ele decida por apenas cancelar o seu agendamento, o sistema iria cancelar apenas o último agendamento realizado, mantendo os *n*-1 agendamentos ativos.

Porém na prática serão raros os casos que entrarão nesta situação de fato e para diminuir a redundância de código, faz sentido em suprimir essa parte.

2020-12-23 18:08 UTC, iago-silva requested changes

2020-12-23 18:08 UTC, iago-silva commented on app/controllers/time_slot_controller.rb
> +      current_patient.appointments.where('start > ?', Time.zone.now).destroy_all
```suggestion
      current_patient.appointments.destroy_all
```

Dessa forma não vai destruir só os agendamentos de um horário específico?

Acredito que a solução deveria ser excluir _todos_ os agendamentos daquele paciente e deixar apenas o novo. 

Ou a regra de negócio permite que um paciente tenha mais de um agendamento marcado?

2020-12-23 18:11 UTC, iago-silva approved these changes

2020-12-24 00:31 UTC, iago-silva commented on app/controllers/time_slot_controller.rb
> +      current_patient.appointments.where('start > ?', Time.zone.now).destroy_all
Seria interessante criar um `scope` para essa busca

```ruby
scope :futures, -> { where('start > ?', Time.zone.now) }
```

2020-12-28 18:02 UTC, iago-silva commented on app/controllers/time_slot_controller.rb
> +      current_patient.appointments.where('start > ?', Time.zone.now).destroy_all
E também pode usar o `Time.current` ao invés do `Time.zone.now`

2021-01-06 14:12 UTC, Mat-Bit commented on app/controllers/time_slot_controller.rb
> +      current_patient.appointments.where('start > ?', Time.zone.now).destroy_all
Oi @iago-silva, obrigado pela sugestão!
Fica mais compreensível e limpo dessa maneira.

Com as alterações, os dois arquivos que tiveram alteração fica assim:

No arquivo ```app/controller/time_slot_controller.rb```:
```ruby
current_patient.appointments.futures.destroy_all
```

E no arquivo ```app/models/appointment.rb```:
```ruby
scope :futures, -> { where('start > ?', Time.current) }
```

2021-01-06 19:03 UTC, iago-silva commented on app/controllers/time_slot_controller.rb
> +      current_patient.appointments.where('start > ?', Time.zone.now).destroy_all
Tá show!

2021-01-06 19:04 UTC, iago-silva approved these changes

2021-01-11 14:09 UTC, merged